root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ."
bin = "tmp/main"
delay = 1000
full_bin = "./tmp/main"

[log]
color = true
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[app]
name = "__MODULE_NAME__"
args = []
watch_dir = ["."]
 exclude = ["tmp", "vendor"]