version: "3.8"

services:
  api-manager:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"    # Puerto de la aplicación
      - "40000:40000"  # Puerto para el debugger
    networks:
      - samm-network
    # Opcional: descomentar si necesitas variables de entorno
    # environment:
    #   - ENV=development

networks:
  samm-network:
    external: true