version: "3.8"

services:
  __MODULE_NAME__:
    build: .
    container_name: __MODULE_NAME__
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "40000:40000"
    expose:
      - "5235"
    networks:
      - samm-network
      
networks:
  samm-network:
    external: true